"""Embedding provider interface (Phase 4 — semantic search).

Implementations: OpenAI text-embedding-3-small (MVP) and an in-memory
deterministic fake for tests. Feature code never imports a vendor SDK
directly — the `EmbeddingProvider` ABC is the only entry point.

`embed` takes a list of strings and returns a list of equal-length
vectors of floats. Implementations are responsible for batching to
respect their provider's per-request input cap; the caller treats
`embed` as a single round-trip from the worker's perspective.

`dimensions` and `model_version` are surface metadata: tasks persist
the model version alongside the vector so a future re-embed campaign
can pick out rows generated by older models.
"""

from __future__ import annotations

from abc import ABC, abstractmethod


class EmbeddingProvider(ABC):
    """Vector embedding provider behind the `Settings.embedding_provider` seam."""

    @abstractmethod
    async def embed(self, texts: list[str]) -> list[list[float]]:
        """Embed each input string. Returns vectors in the same order as `texts`."""
        raise NotImplementedError

    @property
    @abstractmethod
    def dimensions(self) -> int:
        """The fixed dimensionality of vectors this provider returns."""
        raise NotImplementedError

    @property
    @abstractmethod
    def model_version(self) -> str:
        """Stable identifier for the underlying model — persisted with each row."""
        raise NotImplementedError
